# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lh2I7Ask5eABsHs1A35l2ySMCy1y43s8
"""

!pip install torch torchvision
!pip install git+https://github.com/facebookresearch/segment-anything
!pip install opencv-python matplotlib

!mkdir -p modelo
!wget -P modelo https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth

from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
import torch

model_path = "/content/modelo/sam_vit_b_01ec64.pth"

sam = sam_model_registry["vit_b"](checkpoint=model_path)
sam.to(device="cuda" if torch.cuda.is_available() else "cpu")
mask_generator = SamAutomaticMaskGenerator(sam)

import numpy as np
import torch
import matplotlib.pyplot as plt
import cv2

image_path = "/content/images.jpeg"
image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

masks = mask_generator.generate(image)

def show_anns(anns):
    if len(anns) == 0:
        return
    sorted_anns = sorted(anns, key=(lambda x: x['area']), reverse=True)
    ax = plt.gca()
    ax.set_autoscale_on(False)

    img = np.ones((sorted_anns[0]['segmentation'].shape[0], sorted_anns[0]['segmentation'].shape[1], 4))
    img[:,:,3] = 0
    for ann in sorted_anns:
        m = ann['segmentation']
        color_mask = np.concatenate([np.random.random(3), [0.35]])
        img[m] = color_mask
    ax.imshow(img)

plt.imshow(image)
show_anns(masks)
plt.axis('off')
plt.show()